<a href="https://colab.research.google.com/github/gibbyahmad/final_project/blob/master/Predictions.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [0]:
#from google.colab import drive
#drive.mount('/content/drive')

In [0]:
import pandas as pd
import os
import zipfile

In [0]:
#zipfilepath = 'https://drive.google.com/open?id=1nqMHN5e8f1cXu504vxpx011YX6Nkq_gc' 
#csvfilepath = 'https://drive.google.com/open?id=1yKAI8IOk9Cg2hk44r6aYGQHQyeqJD4g2'
filepath = '/content/drive/My Drive/Colab Notebooks/train30k.csv'
df = pd.read_csv(filepath)
#df = pd.read_csv(filepath, error_bad_lines=False, header=None, skiprows=range(0,0), index_col=None)

In [4]:
df.head(6)

Unnamed: 0  ... trafficSource.source
0           0  ...               google
1           1  ...     sites.google.com
2           2  ...             (direct)
3           3  ...               google
4           4  ...               google
5           5  ...             (direct)

[6 rows x 30 columns]

In [0]:
from sklearn.ensemble import RandomForestClassifier
import numpy as np
np.random.seed(0)

In [0]:
df['totals.transactionRevenue'] = df['totals.transactionRevenue'].fillna(0)
revcat = pd.Categorical(df['totals.transactionRevenue']>0)
df['Bought'] = revcat

In [7]:
df['Bought'].value_counts()

False    29679
True       321
Name: Bought, dtype: int64

In [8]:
devcat = pd.Categorical(df['device.deviceCategory'])
df['devcat'] = devcat
df['devcat'].value_counts()

desktop    20955
mobile      8017
tablet      1028
Name: devcat, dtype: int64

In [0]:
devfact = pd.factorize(df['devcat'])[0]
df['Device'] = devfact

In [0]:
# Channel Grouping Category
chgcat = pd.Categorical(df['channelGrouping'])
df['chgcat'] = chgcat
chgfact = pd.factorize(df['chgcat'])[0]
df['Channel'] = chgfact

# Browser 
brcat = pd.Categorical(df['device.browser'])
df['brcat'] = brcat
brfact = pd.factorize(df['brcat'])[0]
df['Browser'] = brfact

# isMobile
mbcat = pd.Categorical(df['device.isMobile'])
df['mbcat'] = mbcat
mbfact = pd.factorize(df['mbcat'])[0]
df['Mobile'] = mbfact

# os
oscat = pd.Categorical(df['device.operatingSystem'])
df['oscat'] = oscat
osfact = pd.factorize(df['oscat'])[0]
df['os'] = osfact

# city
citycat = pd.Categorical(df['geoNetwork.city'])
df['citycat'] = citycat
cityfact = pd.factorize(df['citycat'])[0]
df['City'] = cityfact

# continent
concat = pd.Categorical(df['geoNetwork.continent'])
df['concat'] = concat
confact = pd.factorize(df['concat'])[0]
df['Continent'] = confact

# country
cncat = pd.Categorical(df['geoNetwork.country'])
df['cncat'] = cncat
cnfact = pd.factorize(df['cncat'])[0]
df['Country'] = cnfact

# referral
refcat = pd.Categorical(df['trafficSource.medium'])
df['refcat'] = refcat
reffact = pd.factorize(df['refcat'])[0]
df['Referral'] = reffact

# trafficsource
sourcecat = pd.Categorical(df['trafficSource.source'])
df['sourcecat'] = sourcecat
sourcefact = pd.factorize(df['sourcecat'])[0]
df['TrafficSource'] = sourcefact


#df['chgcat'].value_counts()

In [11]:
df['trafficSource.source'].value_counts()

(direct)                13341
google                   9337
youtube.com              4666
analytics.google.com      649
Partners                  612
                        ...  
lnkd.in                     1
news.ycombinator.com        1
google.it                   1
plus.google.com             1
web.whatsapp.com            1
Name: trafficSource.source, Length: 94, dtype: int64

In [12]:
df.head()

Unnamed: 0 channelGrouping  ...         sourcecat TrafficSource
0           0  Organic Search  ...            google             0
1           1        Referral  ...  sites.google.com             1
2           2          Direct  ...          (direct)             2
3           3  Organic Search  ...            google             0
4           4  Organic Search  ...            google             0

[5 rows x 51 columns]

In [13]:
df['is_train'] = np.random.uniform(0, 1, len(df)) <= .75
df.head()

Unnamed: 0 channelGrouping  ...  TrafficSource is_train
0           0  Organic Search  ...              0     True
1           1        Referral  ...              1     True
2           2          Direct  ...              2     True
3           3  Organic Search  ...              0     True
4           4  Organic Search  ...              0     True

[5 rows x 52 columns]

In [0]:
train, test = df[df['is_train']==True], df[df['is_train']==False]

In [15]:
# Show the number of observations for the test and training dataframes
print('Number of observations in the training data:', len(train))
print('Number of observations in the test data:',len(test))

Number of observations in the training data: 22505
Number of observations in the test data: 7495


In [16]:
df.columns

Index(['Unnamed: 0', 'channelGrouping', 'date', 'fullVisitorId', 'visitId',
       'visitNumber', 'visitStartTime', 'device.browser',
       'device.deviceCategory', 'device.isMobile', 'device.operatingSystem',
       'geoNetwork.city', 'geoNetwork.continent', 'geoNetwork.country',
       'geoNetwork.metro', 'geoNetwork.networkDomain', 'geoNetwork.region',
       'geoNetwork.subContinent', 'totals.bounces', 'totals.hits',
       'totals.newVisits', 'totals.pageviews', 'totals.transactionRevenue',
       'trafficSource.adContent', 'trafficSource.campaign',
       'trafficSource.isTrueDirect', 'trafficSource.keyword',
       'trafficSource.medium', 'trafficSource.referralPath',
       'trafficSource.source', 'Bought', 'devcat', 'Device', 'chgcat',
       'Channel', 'brcat', 'Browser', 'mbcat', 'Mobile', 'oscat', 'os',
       'citycat', 'City', 'concat', 'Continent', 'cncat', 'Country', 'refcat',
       'Referral', 'sourcecat', 'TrafficSource', 'is_train'],
      dtype='object')

In [17]:
ps=len(df.columns)-1
print(ps)
df.columns[ps]

51


'is_train'

In [18]:
#filling up null values
df['totals.transactionRevenue'] = df['totals.transactionRevenue'].fillna(0)
df['date'] = df['date'].fillna(0)
df['visitNumber'] = df['visitNumber'].fillna(0)
df['visitStartTime'] = df['visitStartTime'].fillna(0)
df['totals.bounces'] = df['totals.bounces'].fillna(0)
df['totals.hits'] = df['totals.hits'].fillna(0)
df['totals.newVisits'] = df['totals.newVisits'].fillna(0)
df['totals.pageviews'] = df['totals.pageviews'].fillna(0)
df['trafficSource.isTrueDirect'] = df['trafficSource.isTrueDirect'].fillna(0)

# Create a list of the feature column's names
pos = [5, 19, 32, 34, 36, 38, 40, 42, 44, 46, 48, 50]
features = df.columns[pos]

# View features
features

Index(['visitNumber', 'totals.hits', 'Device', 'Channel', 'Browser', 'Mobile',
       'os', 'City', 'Continent', 'Country', 'Referral', 'TrafficSource'],
      dtype='object')

In [19]:
y = pd.factorize(train['Bought'])[0]
y

array([0, 0, 0, ..., 0, 0, 0])

In [20]:
# Create a random forest Classifier. By convention, clf means 'Classifier'
clf = RandomForestClassifier(n_jobs=2, random_state=0)

# Train the Classifier to take the training features and learn how they relate
# to the training y (the species)
clf.fit(train[features], y)

/usr/local/lib/python3.6/dist-packages/sklearn/ensemble/forest.py:245: FutureWarning: The default value of n_estimators will change from 10 in version 0.20 to 100 in 0.22.
  "10 in version 0.20 to 100 in 0.22.", FutureWarning)


RandomForestClassifier(bootstrap=True, class_weight=None, criterion='gini',
                       max_depth=None, max_features='auto', max_leaf_nodes=None,
                       min_impurity_decrease=0.0, min_impurity_split=None,
                       min_samples_leaf=1, min_samples_split=2,
                       min_weight_fraction_leaf=0.0, n_estimators=10, n_jobs=2,
                       oob_score=False, random_state=0, verbose=0,
                       warm_start=False)

In [21]:
# Apply the Classifier we trained to the test data (which, remember, it has never seen before)
clf.predict(test[features])

array([0, 0, 0, ..., 0, 0, 0])

In [22]:
# View the predicted probabilities of the first 10 observations
clf.predict_proba(test[features])[0:10]

array([[1., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.]])

In [0]:
# Create actual english names for the plants for each predicted plant class
preds = df['Bought'][clf.predict(test[features])]

In [24]:
# View the PREDICTED species for the first five observations
preds[0:5]

0    False
0    False
0    False
0    False
0    False
Name: Bought, dtype: category
Categories (2, object): [False, True]

In [25]:
test['Bought'].head()

7     False
8     False
10    False
13    False
17    False
Name: Bought, dtype: category
Categories (2, object): [False, True]

In [26]:
# Create confusion matrix
pd.crosstab(test['Bought'], preds, rownames=['Actually Bought'], colnames=['Predicted'])

Empty DataFrame
Columns: []
Index: []

In [27]:
# View a list of the features and their importance scores
list(zip(train[features], clf.feature_importances_))

[('visitNumber', 0.12458540463794837),
 ('totals.hits', 0.49303563861006383),
 ('Device', 0.005833731971128687),
 ('Channel', 0.054807442506310755),
 ('Browser', 0.02412904348876367),
 ('Mobile', 0.006175974032650244),
 ('os', 0.058585839868412766),
 ('City', 0.15001540469225236),
 ('Continent', 0.009276862810831428),
 ('Country', 0.029129781507494405),
 ('Referral', 0.017434434005165523),
 ('TrafficSource', 0.02699044186897782)]